---
name: "Test"
on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled

jobs:
  test:
    name: "Test building binaries"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: "Test build"
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          toolchain: 1.79.0
          use-cross: true
          command: test
          args: --release --target=${{ matrix.target }}
